pepewsFootwear/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, register_converter
from django.conf.urls.static import static
from .views import *

urlpatterns = [
    path('', indexMain, name='indexMain'),
    path('product/<str:pk>', indexProduct, name='indexProduct'),
    path('classy/', classy, name='classy'),
    path('sporty/', sporty, name='sporty'),
    path('trendy/', trendy, name='trendy'),
    path('transaction/', indexTransaction, name='indexTransaction'),
    path('review/<str:pk>', indexReview, name='indexReview'),
    path('postReview/<str:pk>', postReview, name='postReview'),
    path('coupon/', coupon, name='coupon'),
    path('payment/', payment, name='payment'),
    path('login/', loginFunc, name='login'),
    path('logout/', logoutFunc, name='logout'),
    path('signup/', signup, name='signup'),
    # path('test/', testing, name='testing'),
]

ppw_tk1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pepewsFootwear.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pepewsFootwear/models.py
from django.db import models
from django.core.validators import *
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.contrib.auth.models import User

# Create your models here.


class Style(models.Model):
    pilihanStyle = (
        ('Classy', 'Classy'),
        ('Trendy', 'Trendy'),
        ('Sporty', 'Sporty')
    )
    nama = models.CharField(max_length=120, choices=pilihanStyle)

    def __str__(self):
        return self.nama


class Product(models.Model):

    nama = models.CharField(max_length=120)
    harga = models.IntegerField()
    deskripsi = models.TextField()
    style = models.ForeignKey(Style, null=True, on_delete=models.SET_NULL)
    stok = models.IntegerField()
    gambar = models.TextField()

    def __str__(self):
        return self.nama


class Review(models.Model):

    pilihanRate = (
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
    )
    produk = models.ForeignKey(Product, null=True, on_delete=models.SET_NULL)
    pengulas = models.ForeignKey(User, on_delete=models.CASCADE)
    headline = models.CharField(max_length=150)
    ulasan = models.TextField()
    bintang = models.IntegerField(choices=pilihanRate, default=5)
    tanggal = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.headline + " "+ self.produk.nama


class Transaction(models.Model):

    orderId = models.CharField(max_length=120)
    customer = models.CharField(max_length=120)
    transDate = models.DateTimeField(auto_now=True)
    produk = models.ForeignKey(Product, null=True, on_delete=models.SET_NULL)
    noHP = models.CharField(max_length=12)
    alamat = models.TextField()

    def __str__(self):
        return self.customer


class Coupon(models.Model):
    nama = models.CharField(max_length=100, null=True)
    deskripsi = models.TextField(null=True)
    kode = models.CharField(max_length=100)
    persen = models.CharField(max_length=100)
    tanggal = models.DateField()
    harga = models.IntegerField(default=10000)

    def __str__(self):
        return '{}'.format(self.nama)

pepewsFootwear/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class TransactionCreateForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = '__all__'
        widgets = {
            'orderId': forms.HiddenInput(attrs={
                'class': 'form-control'
            }),
            'customer': forms.TextInput(attrs={
                'class': 'form-control'
            }),
            'produk': forms.HiddenInput(attrs={
                'class': 'form-control'
            }),
            'transDate': forms.HiddenInput(attrs={
                'class': 'form-control'
            }),
            'noHP': forms.TextInput(attrs={
                'class': 'form-control'
            }),
            'alamat': forms.Textarea(attrs={
                'class': 'form-control'
            }),
        }


class ReviewPageCreateForm(forms.Form):
    pilihanRate = (
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
    )
    headline = forms.CharField(required = False ,widget= forms.TextInput(attrs={
        'class': 'form-control',
        'type': 'text',
        'placeholder': 'Plese enter your headline',
    }))
    ulasan = forms.CharField(required = False, widget= forms.Textarea(attrs={
        'class': 'form-control',
        'type': 'text',
        'placeholder': 'Please enter your review',
    }))
    bintang = forms.IntegerField(required=False,widget= forms.Select(choices = pilihanRate,attrs={
        'class': 'form-control',
        'placeholder' : 'Please enter the star',
    }))


class SearchForm(forms.Form):
    coupon = forms.CharField(widget=forms.TextInput(attrs={'class':'searchbox', 'type':'text', 'id':'listinput'}))


class PaymentForm(forms.Form):
    choices = [
        ("Debit card","Debit Card") ,
        ("Credit card","Credit card"),
    ]
    payment = forms.ChoiceField(widget=forms.RadioSelect(attrs={}), choices=choices)
    card_number = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))


class loginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type': 'text',
        'title': 'Username',
        'placeholder': 'Plese enter your username',
        'required': True,
    }))
    password = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type': 'password',
        'placeholder': 'Plese enter your password',
        'required': True,
    }))


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(
        max_length=30, required=True, help_text='Enter your first name.')
    last_name = forms.CharField(
        max_length=30, required=True, help_text='Enter your last name.')
    email = forms.EmailField(
        max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name',
                  'email', 'password1', 'password2', )

pepewsFootwear/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from datetime import datetime, date
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.db.models import Q
from django.template.loader import render_to_string
from django.http import JsonResponse

# Create your views here.


def indexMain(request):
    return render(request, 'landingPageNew.html')


def indexProduct(request, pk):
    selectedProduct = Product.objects.get(id=pk)
    orderIdTmp = datetime.now().strftime("%m%d%Y%H%M%S")+selectedProduct.nama
    print(orderIdTmp)
    initial_data = {
        'orderId': orderIdTmp,
        'transDate': datetime.now(),
        'produk': selectedProduct,
    }
    form = TransactionCreateForm(request.POST or None, initial=initial_data)
    print(initial_data)
    reviews = Review.objects.filter(produk=selectedProduct)
    if form.is_valid():
        print('save berhasil')
        form.save()
        selectedProduct.stok -= 1
        selectedProduct.save()
        messages.success(request, 'Produk berhasil dipesan')
    else:
        print(form.errors)
        print("gagal")

    context = {
        'selectedProduct': selectedProduct,
        'form': form,
        'reviews': reviews,
    }
    return render(request, 'productPage.html', context)


def indexTransaction(request):
    transactions = Transaction.objects.all()

    context = {
        'transactions': transactions,
    }
    return render(request, 'transactionPage.html', context)


def classy(request):
    return render(request, 'classy.html', {'classy_list': Product.objects.filter(style__nama__contains='Classy')})


def sporty(request):
    return render(request, 'sporty.html', {'sporty_list': Product.objects.filter(style__nama__contains='Sporty')})


def trendy(request):
    return render(request, 'trendy.html', {'trendy_list': Product.objects.filter(style__nama__contains='Trendy')})


def testing(request):
    return render(request, 'test.html')


def indexReview(request, pk):
    user = request.user
    form = ReviewPageCreateForm()
    selectedProduct = Product.objects.get(id=pk)
    data = {
        'produk': selectedProduct
    }
    review = Review.objects.filter(produk=selectedProduct)
    total = 0
    jumlah_bintang_1 = 0
    jumlah_bintang_2 = 0
    jumlah_bintang_3 = 0
    jumlah_bintang_4 = 0
    jumlah_bintang_5 = 0
    for rev in review:
        total += rev.bintang
        if rev.bintang == 1:
            jumlah_bintang_1 += 1
        elif rev.bintang == 2:
            jumlah_bintang_2 += 1
        elif rev.bintang == 3:
            jumlah_bintang_3 += 1
        elif rev.bintang == 4:
            jumlah_bintang_4 += 1
        elif rev.bintang == 5:
            jumlah_bintang_5 += 1
    try:
        avg = total / len(review)
        avg = round(avg, 2)
    except ZeroDivisionError:
        avg = 0
    avg = round(avg, 2)
    context = {
        'selectedProduct': selectedProduct,
        'review': review,
        'average': avg,
        'form' : form,
        'postPK' : pk,
        'user' : user,
        'bintang1': jumlah_bintang_1,
        'bintang2': jumlah_bintang_2,
        'bintang3': jumlah_bintang_3,
        'bintang4': jumlah_bintang_4,
        'bintang5': jumlah_bintang_5

    }
    return render(request, 'reviewPage.html', context)

def postReview(request, pk) :
    selectedProduct = Product.objects.get(id=pk)
    data ={
        'produk' : selectedProduct
    }
    response_data = {}
    if request.method == "POST":
        print(request.POST)
        headline = request.POST.get('headline')
        ulasan = request.POST.get('ulasan')
        bintang = request.POST.get('bintang')

        response_data['headline'] = headline
        response_data['ulasan'] = ulasan
        response_data['bintang'] = bintang
        response_data['tanggal'] = datetime.now().strftime("%m-%d-%Y")

        Review.objects.create(produk = selectedProduct, pengulas = request.user,
        headline = headline, ulasan = ulasan, bintang = bintang)
        return JsonResponse(response_data)

def coupon(request):
    form = SearchForm()
    if 'coupon' in request.GET:
        result = str(request.GET['coupon']).lower()
        coupons = list(Coupon.objects.all())
        hasil = []
        for i in coupons:
            if (result in i.nama.lower() or result in str(i.persen) or result in i.kode.lower()):
                hasil.append(i)        
        return render(request, 'coupon.html',{"form":form, "hasil": hasil,})

    return (render(request, 'coupon.html',{'coupon': list(Coupon.objects.all()), 'form':form }))


def loginFunc(request):
    form = loginForm()
    if(request.method == "POST"):
        form = loginForm(request.POST)
        if(form.is_valid()):
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if(user is not None):
                login(request, user)
                return redirect('/login/')
            else:
                messages = ['Incorrect username or password']
                response = {'form': form, 'messages': messages}
                return render(request, 'login.html', response)
    else:
        response = {'form': form}
        return render(request, 'login.html', response)


def logoutFunc(request):
    logout(request)
    return redirect('/login/')


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/login/')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})

def payment(request):
    # Instantiate object of searhform and paymentform
    paymentForm = PaymentForm()
    # Setting up context for template
    context = {'paymentForm':paymentForm}
    # Check if query q exists
    url_parameter = str(request.GET.get('q'))
    print(request)
    print("ini url_parameter " + url_parameter)
    
    # Define variable coupons
    coupons = []
    if url_parameter:
        print("ini nyari berdasarkan q")
        counter =0
        for coupon in Coupon.objects.all():
            if coupon.persen >= url_parameter:
                coupons.append((coupon, counter))
                counter +=1  
            if len(coupons) >= 3:
                break

    # Adding coupons to context
    if coupons:
        context["coupons"] = coupons
    print(context)
    print("ini semua coupon ", Coupon.objects.all())

    # Handle AJAX request
    if request.is_ajax():
        print("masuk if ajax")
        html = render_to_string(template_name='couponajax.html', context={'coupons':coupons})
        print(html)
        data = {'html':html}
        return JsonResponse(data=data, safe=False)

    return render(request,'payment.html', context=context)

pepewsFootwear/templates/classy.html
{% extends 'includes/base.html' %}
{% load static %}
{% block title %} Classy {% endblock %}

{% block content %}
<div class="container-fluid padding top-classy">
    <h1 class="title">only for the<br>finest gentlemen.</h1>
</div>

<div class="container-fluid padding mid">
    <div class="row text-center padding">
        <div class="col-sm-6">
            <img src="{% static 'formal3.jpg' %}" alt="shoe" class="big">
        </div>
        <div class="col-sm-6 definition">
            <h3>classy</h3>
            <h4 class="subtitle">/ˈklasē/</h4>
            <p>(adj.) stylish and sophisticated.</p>
        </div>
    </div>
</div>

<div class="container-fluid padding bot">
    <div class="row text-center">
        {% for i in classy_list %}
        <div class="col-sm-6 col-md-4 boxdown">
            <a href="/product/{{i.id}}">
                <div class="hover hover-2 text-white rounded"><img src={{i.gambar}} alt="" class="expad">
                    <div class="hover-overlay"></div>
                    <div class="hover-2-content px-5 py-4">
                        <h3 class="hover-2-title text-uppercase font-weight-bold mb-0">{{i.nama}}</h3>
                        <p class="hover-2-description text-uppercase mb-0">{{i.harga}}$</p>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

pepewsFootwear/templates/couponajax.html
{% load static %}
{% if coupons %}
    <script>
        $("#redeemButton0").click( ()=> {
            let totalPembelian = $("#totalPembelian").val()
            totalPembelian -= ($("#redeemButton0").val()/100)*totalPembelian
            $("div#replaceTotal").html("<param id='totalPembelian' value=130 >Discount applied! New total "+totalPembelian+"</param>")
        })
        $("#redeemButton1").click( ()=> {
            let totalPembelian = $("#totalPembelian").val()
            totalPembelian -= ($("#redeemButton1").val()/100)*totalPembelian
            $("div#replaceTotal").html("<param id='totalPembelian' value=130 >Discount applied! New total "+totalPembelian+"</param>")
        })
        $("#redeemButton2").click( ()=> {
            let totalPembelian = $("#totalPembelian").val()
            totalPembelian -= ($("#redeemButton2").val()/100)*totalPembelian
            $("div#replaceTotal").html("<param id='totalPembelian' value=130 >Discount applied! New total "+totalPembelian+"</param>")
        })
    </script>
    
    {% for coupon,counter in coupons %}
    <div class="dropdown-item display-4">
        <p>{{coupon.nama}} {{coupon.persen}}% </p>
        <img style="width: 10rem; height: 10rem;" class="img-fluid" src="{% static 'disc.png' %}" alt="Image of Coupon"><button type="button" class="btn btn-secondary" value="{{coupon.kode}}" id="redeemButton{{counter}}">Redeem</button>
    </div>
    {% endfor %}
    </div>
{% endif %}

pepewsFootwear/templates/login.html
{% extends 'includes/base.html' %}
{% load static %}
{% load humanize %}
{% load socialaccount %}
{% block title %} Sign in {% endblock %}
{% block content %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-success alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}
{% endif %}
<div class="col-12 col-md-6 col-lg-4 mx-auto">
    <div class="card mx-auto text-center" style="width:100% ;margin-top: 20vh; margin-bottom: 20vh;">
        <br>
        {% if user.is_authenticated %}
        <span class="mx-auto" style="text-transform: capitalize;" id="user-display">Hello, {{ user }}</span>
        <a class="btn btn-outline-dark mx-auto" href="{% url 'logout' %}" id='logout' style="width: 300px;">Logout</a>
        <br>
        {% else %}
        <div class='form'>
            <form action="" method="POST" style="margin: 0; padding: 0;">
                <div class="mx-auto" style="width: 300px;">
                    {% csrf_token %} {{ form }}
                </div>
                <br>
                <input type="submit" class="btn btn-outline-dark" style="width: 300px; margin-left: 5px;" value="Login"
                    id="submit">
                <br>
            </form>
        </div>
        <a href="{% provider_login_url "google" %}" class="btn btn-outline-dark mx-auto"
            style="width: 300px; margin-top:1vh;">
            Login with Google
        </a>
        <br>
        <span>
            Don't have an account? Sign up <a href="{% url 'signup' %}" style="color: rgb(148, 148, 148);"
                id="sign-up">here</a>!
        </span>
        <br>
        {% endif %}
    </div>
</div>
{% if user.is_authenticated %}
<div class="filler" style="height: 20vh;"></div>
{% endif %}
{% endblock %}

pepewsFootwear/templates/reviewPage.html
{% extends 'includes/base.html' %}
{% load static %}
  
{% block title %} 
Review Page
{% endblock %}


    {% block content %}
    <br>
    <br>
    <div class="container-fluid mb-5 pb-5" style="background: rgba(255, 254, 250, 0.9);; box-shadow: 4px 4px 20px rgba(0, 0, 0, 0.25);">
        <div class="row pt-5 mt-5 pl-5 ml-5">
          <div class="col-md-12">
            <h2>{{selectedProduct.nama}}</h2>
            <br>
          </div>
        </div>
        <div class="row pt-5">
          <div class="col-md-12 text-center">
            <img src="{{ selectedProduct.gambar }}" 
            alt="ProductImage" class="img-fluid mx-auto d-block">
          </div>
        </div>
        <div class="row pt-5">
          <div class="col-md-12 text-center">
            <div class="d-flex justify-content-center">
              <a href="#formReview"><button type="button" class="btn btn-outline-secondary" >Make Review</button></a>
            </div>
          </div>
        </div>
    </div>

    <section id="userrating">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <h2>Average User Rating</h2>
            <br>
            {% if average > 0 %}
              <h2 style="font-size: 50px;" class="text-left pl-5 ml-3">{{average}}/5.00</h2>
            {% else %}
              <h2 style="font-size: 50px;" class="text-left pl-5 ml-3">NoRating</h2>
            {% endif %}
          </div>
          <div class="col-md-6">
            <h2>Rating Breakdown</h2>
            <br>
            <div class="row">
              <div class="col-md-1">
                <h5>5</h5>
              </div>
              <div class="col-md-1">
                <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
             </div>
              <div class="col-md-6">
                <div class="alert alert-primary" role="alert" style="width: 100%;"></div>
              </div>
              <div class="col-md-1">
                <h5>{{bintang5}}</h5>
              </div>
            </div>

            <div class="row">
              <div class="col-md-1">
                <h5>4</h5>
              </div>
              <div class="col-md-1">
                <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
             </div>
              <div class="col-md-6">
                <div class="alert alert-primary" role="alert" style="width: 80%;"></div>
              </div>
              <div class="col-md-1">
                <h5>{{bintang4}}</h5>
              </div>
            </div>

            <div class="row">
              <div class="col-md-1">
                <h5>3</h5>
              </div>
              <div class="col-md-1">
                <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
             </div>
              <div class="col-md-6">
                <div class="alert alert-primary" role="alert" style="width: 60%;"></div>
              </div>
              <div class="col-md-1">
                <h5>{{bintang3}}</h5>
              </div>
            </div>

            <div class="row">
              <div class="col-md-1">
                <h5>2</h5>
              </div>
              <div class="col-md-1">
                <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
             </div>
              <div class="col-md-6">
                <div class="alert alert-primary" role="alert" style="width: 40%;"></div>
              </div>
              <div class="col-md-1">
                <h5>{{bintang2}}</h5>
              </div>
            </div>

            <div class="row">
              <div class="col-md-1">
                <h5>1</h5>
              </div>
              <div class="col-md-1">
                <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
             </div>
              <div class="col-md-6">
                <div class="alert alert-primary" role="alert" style="width: 20%;"></div>
              </div>
              <div class="col-md-1">
                <h5>{{bintang1}}</h5>
              </div>
            </div>

          </div>
        </div>
        </div>
        <hr style="border: 1px solid #000000;">
    </section>
    
    <section id="reviews">
      <div class="container-fluid pt-5">
        <div class="row">
          <div class="col ml-5">
            <h2>All Reviews</h2>
          </div>
        </div>
      </div>
      {%for i in review%}
      <div class="container pt-5">
        <div class="row">
          <div class="col-md-4 ml-5">
            <h2 style=" font-size: 50px;">{{i.bintang}}.0</h2>
            {%if i.bintang == 0 %}
              <i class="fa fa-star fa-lg"></i>
              <i class="fa fa-star fa-lg"></i>
              <i class="fa fa-star fa-lg"></i>
              <i class="fa fa-star fa-lg"></i>
              <i class="fa fa-star fa-lg"></i>
            {% elif i.bintang == 1 %}
              <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
              <i class="fa fa-star fa-lg"></i>
              <i class="fa fa-star fa-lg"></i>
              <i class="fa fa-star fa-lg"></i>
              <i class="fa fa-star fa-lg"></i>
            {% elif i.bintang == 2 %}
              <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
              <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
              <i class="fa fa-star fa-lg"></i>
              <i class="fa fa-star fa-lg"></i>
              <i class="fa fa-star fa-lg"></i>
            {% elif i.bintang == 3 %}
              <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
              <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
              <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
              <i class="fa fa-star fa-lg"></i>
              <i class="fa fa-star fa-lg"></i>
            {% elif i.bintang == 4 %}
              <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
              <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
              <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
              <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
              <i class="fa fa-star fa-lg"></i>
            {% elif i.bintang == 5 %}
              <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
              <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
              <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
              <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
              <i class="fa fa-star fa-lg" style="color: #ffff00;"></i>
            {% endif %}
          </div>
          <div class="col-md-5 mr-5 ml-5">
            <h5 style="font-size: 25px;"><b>{{i.headline}} <i>- {{i.pengulas}} </i></b></h5>
            <h6 style="font-size: 18px; text-align: justify;">{{i.ulasan}}</h6>
            <h6><b>{{i.tanggal}}</b></h6>
          </div>
        </div>
      </div>
      <br>
      <hr>
      {% endfor %}
      <div id="dataReview"></div>
      <hr style="border: 1px solid #000000;">
    </section>
  <section class="form" id="formReview">
  {% if user.is_authenticated %}
    <div class="container-fluid pb-5 mt-5">
      <form method="POST" id="reviewForm">
        {% csrf_token %}
        <div class="row">
          <h2>Review Now</h2>
        </div>
        <div class="row pt-5">
          <div class="col-md-6">
            <h4> <i class="fas fa-envelope"></i> Title</h4>
            <div id="headline">{{form.headline}}</div>
            <br>
            <h4> <i class="fas fa-envelope"></i> Your Message</h4>
            <div id="ulasan">{{form.ulasan}}</div>
            <br>
            <h4>Rate Us</h4>
            <div id="bintang">{{form.bintang}}</div>
            <div id="tanggal">{{form.tanggal}}</div>
          </div>
        </div>
        <div class="row pt-5">
          <input type = "submit" id='submitReview' class="btn btn-dark mx-auto" value="Submit" style="font-size: 20px;" >
        </div>
      </form>
    </div>
  {% else %}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-5">
                <h4>You have to Login first to fill the form</h4>
            </div>
        </div>
        <div class="row justify-content-center mb-3">
            <div class="col-md-2">
                <a href="{% url 'login' %}"><button type="button" class="btn btn-outline-secondary">Back to Login Page</button></a>
            </div>
        </div>
    </div>
  </section>
  {% endif %}
  {% endblock %}

  {% block script %} 
    <script src="https://kit.fontawesome.com/a48052e337.js" crossorigin="anonymous"></script>
    <script src="http://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script type="text/javascript">
        $(document).on('submit','#reviewForm', function(e){
          e.preventDefault();
          $.ajax({
            type: 'POST',
            url: "{% url 'postReview' postPK %}",
            data:{
              headline:$('#id_headline').val(),
              ulasan:$('#id_ulasan').val(),
              bintang:$('#id_bintang').val(),
              tanggal:$("#id_tanggal").val(),
              csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
              action: 'post'
            },
            success:function(json){
              $("#reviewForm").trigger('reset');
              $("#dataReview").prepend(
                '<div class="container pt-5">' + '<div class="row">' + '<div class="col-md-4 ml-5">' +
                '<h2 style=" font-size: 50px;">' + json.bintang +'.0</h2>' +'</div>' + '<div class="col-md-5 mr-5 ml-5">' 
                + '<h5 style="font-size: 25px;">' + '<b>' + json.headline + '<i>' + ' - {{ user.get_username }}' + 
                '</i>' +'</b>'+'</h5>' + '<h6 style="font-size: 18px; text-align: justify;">' + json.ulasan
                + '</h6> <h6><b>' + json.tanggal + '</h6></div></div></div><br><hr>'
              )
            },
            error : function(xhr,errmsg,err) {
            console.log(xhr.status + ": " + xhr.responseText);
            }
          })
        })

    </script>
{% endblock %}

pepewsFootwear/templates/test.html
{% extends 'includes/base.html' %}
{% block content %}
<div class="page-scroll" style="height: 100vh;"></div>
{% endblock %}